version: '3.8'

services:
  api:
    build: .
    restart: always
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    container_name: api-template
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass1234
    ports:
      - "27017:27017"
    container_name: mongo-db